Repository ISISComputingGroup/EPICS-upgrade, pull requests merged in 2020-01, with the labels that each got.

#34 Ticket4913 muon begin end commands
  src/common_upgrades/utils/constants.py
  src/upgrade_step_check_init_inst.py
  test/test_upgrade_step_check_init_inst.py
  upgrade.py
Labels: size/L

#35 Add dashboard PVs to config area
  data/dashboard.db
  data/dashboard_muon.db
  src/upgrade_step_from_5p6p0.py
  upgrade.py
Labels: size/L

#37 Update to 6.0.0
  upgrade.py
Labels: size/XS

#36 Values and labels in database file to be archived
  data/dashboard.db
  data/dashboard_muon.db
Labels: size/M
