Repository ISISComputingGroup/EPICS-upgrade, pull requests merged in 2022-05, with the labels that each got.

#65 Ticket7134 upgrade step added to remove reflectometry OPI from device screens in instrument configs
  src/file_access.py
  src/upgrade_step_from_10p0p0.py
  test/test_upgrade_step_from_10p0p0.py
  upgrade.py
Labels: size/L

#66 Use unix style paths (breaks rhel build otherwise)
  src/upgrade_step_from_10p0p0.py
Labels: size/XS

#67 fixes couldnt find file problem
  src/upgrade_step_from_10p0p0.py
  test/test_upgrade_step_from_10p0p0.py
Labels: size/S
